### PR TITLE
Enhanced maven build, use java 8, removed profile, use default maven …

### PR DESCRIPTION
**Pull request by ManuelB**
…folders, enhanced compatibility with m2e

### CODE REVIEW

**Comment by ManuelB** [comment]
Hi @saschadoemer,
first let me explain in more detail why we made these changes:

 1. Renamed definitions to agrirouter-api-protobuf-definitions

We have the convention in our company that the maven artifacts should have the same name like the repository. I don't see a reason why this shouldn't be done here.

 2. Removed the profile

We are using maven as well for our builds and eclipse. In our default configuration we are using no profiles at all. I don't see a point in using a profile here. You could just delete the documentation in the build configs.

 3. Use java 8

This is not really required but maybe later the google protobuf generators will use Java 8 features and this will make sure that it will work with java 8

 4. Removed source src/main/generated

In maven the default behavior of putting generated sources is to place it in target/generated-sources (https://maven.apache.org/guides/mini/guide-generating-sources.html). We are typically using these projects in eclipse with m2e integration and when using the default folders they are automatically added to the build path in eclipse.

Is it possible that the DKE publishes the correctly generated Java 8 builds on maven central? This would make it a lot easier to consume for java and maven users and we are not required to build and manage these libaries on our own.

I will also send an email to the DKE management asking for a deployment on maven central.

I can do this under the coordinates de.incentergy but I don't know if this is allowed from a License perspective.

An example of publishing artifacts can be find here:
https://github.com/thomasjungblut/tjungblut-math/issues/2

and here:

https://github.com/ManuelB/java-bean-to-code-serializer/issues/2

**Comment by saschadoemer** [comment]
Hey @ManuelB 

totally fine with the renaming of the artifact id, no problem at this point. 

I will need the profiles to ensure a CI build on travis which will - and this is the most relevant part - deploy the artifact to maven central. SNAPSHOT is already available, see other open PRs. Update will follow soon.

I'm totally fine with this, but this should be done in another way, please open up an issue on this and I'll provide a solution using the CI.

Sources are places underneath ´src/main/generated´ to deliver a fully functional maven artifact without having the need to modify the path inside the JAR.

All of your problems are eliminated with PR #15 which places a SNAPSHOT on Maven Central, I already recognized the need and established a build pipeline.

😺 😺 😺

**Comment by ManuelB** [comment]
@saschadoemer I opened an issue here:

https://github.com/DKE-Data/agrirouter-api-protobuf-definitions/issues/17

I also saw that the pull requests puts the source under the Apache 2 License. This is very good to see.

If we can help more let us know.

**Comment by saschadoemer** [comment]
You could - feel free to file an issue for JDK8, JDK9, etc. This would keep up the pace of the project.

**Comment by ManuelB** [comment]
@saschadoemer our internal policy is to only use LTS versions of Java. So we currently only care about Java 8. Some of our libraries are already compiled with Java 9. They work but some annotation indexers like Jandex throw exceptions.

**Comment by ManuelB** [comment]
Done: https://github.com/DKE-Data/agrirouter-api-protobuf-definitions/issues/18

**Comment by saschadoemer** [comment]
@ManuelB I would abandon this PR. The changes to the coordinates are part of the upcoming PR including classifiers. If you have any other changes, let me know.

**Pull request closed without merging**
